### ISSUE TITLE
Please consider handling BINARY(20)

### ISSUE THREAD

**Issue by ParensAllTheWayDown** [narendrans/dremio-snowflake#10]
**What would you like to be added**:

I ran into a stack trace with one of our source tables...  it looks like there is no handler for BINARY data type. 

```
2019-08-12 13:13:05,217 [qtp750518820-243] WARN  c.d.e.store.jdbc.dialect.TypeMapper - A column you queried has a data type that is not currently supported by the JDBC storage plugin. The column's name was FOO.BAR.BAZ.KEY, its JDBC data type was BINARY, and the source column type was BINARY.
```

I tried to follow your example in `snowflake-arp.yaml`:

```
    #------------Binary types--------------#
    - source:
        name: "BINARY"
      dremio:
        name: "varbinary"
```

But not having success yet.
 

**Why is this needed**:
In Snowflake, we have columns defined as:

```
BINARY(20)
```
